name: Deploy kafka to dev and prod
on:
  push:
    branches:
      - main
    paths:
      - 'dinesykmeldte-kafka/**'
      - '.github/workflows/deploy-kafka.yml'
      - 'build.gradle.kts'

jobs:
  jar-app:
    uses: navikt/teamsykmelding-github-actions-workflows/.github/workflows/jar-app.yaml@main
    secrets: inherit
    with:
      app: dinesykmeldte-kafka
      dockerfile_path: ./dinesykmeldte-kafka/Dockerfile
      docker_context: dinesykmeldte-kafka
      subprojects: true
      naiserator_dev: dinesykmeldte-kafka/naiserator-dev.yaml
      naiserator_prod: dinesykmeldte-kafka/naiserator-prod.yaml
