name: Deploy kafka to dev and prod
on: push

jobs:
  jar-app:
    uses: navikt/teamsykmelding-github-actions-workflows/.github/workflows/jar-app.yaml@main
    secrets: inherit
    with:
      app: dinesykmeldte-kafka
      dockerfile_path: ./dinesykmeldte-kafka/Dockerfile
      docker_context: dinesykmeldte-kafka
      subprojects: true